# _config.yml
description: "Autonomy, GNC, dense perception, and safety-critical robotics."
theme: minima

# Optional: social + markdown settings
markdown: kramdown
kramdown:
  input: GFM

url: "https://skannah.github.io"
baseurl: ""

plugins:
  - jekyll-remote-theme

remote_theme: minima

