# _config.yml
description: "Autonomy, GNC, dense perception, and safety-critical robotics."
theme: minima

# Optional: social + markdown settings
markdown: kramdown
kramdown:
  input: GFM

url: "https://skannah.github.io"
baseurl: ""

<div style="display:flex; gap:20px; flex-wrap:wrap; justify-content:center; margin-top:10px; margin-bottom:20px;">
  <a href="projects.md">Projects</a>
  <a href="research.md">Research Interests</a>
  <a href="courses.md">Graduate Coursework</a>
</div>

plugins:
  - jekyll-remote-theme

remote_theme: minima

